| Category                       | Components / Description                                                                                                                                                                                                                                                                           |
| ------------------------------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **Programming language**       | Python 3                                                                                                                                                                                                                                                                                           |
| **Execution environments**     | Local development environment (Linux / Windows paths observed)<br>Google Colab (optional notebook runtime)<br>Google Drive (mounted storage for input/output files in Colab)                                                                                                                       |
| **Libraries and frameworks**   | `pandas` (dataframe construction, transformation, CSV export)<br>Python standard library:<br>   • `pathlib` (path management)<br>   • `json` (JSON parsing)<br>`google.colab` (optional Drive mounting in Colab)                                                                                   |
| **Data sources**               | Web Annotation JSON export containing Ukrainian Folk Art annotations<br>Europeana-derived annotation records imported from `5_ukrainian-folkart_annotations.json`                                                                                                                                  |
| **Data formats**               | JSON (`.json`) for annotation input<br>CSV (`.csv`) for analysis-ready export                                                                                                                                                                                                                      |
| **Data processing / analysis** | Transformation of Web Annotation JSON into normalized tabular data<br>Extraction of annotation fields including:<br>   • annotation value<br>   • Europeana object identifier<br>   • upvotes / downvotes<br>   • recommendation status<br>Date normalization and dataframe sorting using `pandas` |
| **Outputs**                    | Analysis-ready CSV file: `5_ukrainian-folkart-annotations.csv`<br>Normalized dataframe for statistical inspection and downstream analysis<br>Summary statistics for annotation recommendation categories (`accept`, `reject`, `unknown`)                                                           |
